currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 100
    minimalForWeight: 10
    perM3: 100
    minimalForVolume: 10

coordinates:
  latitudeMin: 45
  latitudeMax: 65
  longitudeMin: 30
  longitudeMax: 96